### ISSUE TITLE
Issue #18 – How to model groups that are present at different places at the same time?

### ISSUE THREAD

**Issue by chin-rcip** [chin-rcip/chin-rcip#18]
For the moment, we used the sojourn pattern to model the location of persons and groups.
But some groups, like Kodak, are at many places at the same time. How do we model that?

1)	Do we just have multiple sojourn at the same time?
2)	Do we use another pattern for groups, that could be acquisition or location of places.

**Comment by KarineLeonardBrouillet** [comment]
Intuitively I would say that the second option would be closer to reality as the idea of a sojourn, especially for a company, seems weird especially considering that sojourns are temporary stays in locations that are not one's customary residence. A constellation of people can sojourn (like a group vacationing together for example) but a corporate body cannot I think? Companies are usually incorporated in places and can change the location of their head offices for example, but what would a sojourn amount to? A change in the head office location? So for incorporated actors, the second option seems more accurate if using acquisition, but it would be problematic for simple constellations of people who are really just sojourning. In this instance, could the individual actors' sojourns be inferred and created (pattern 1) based on the location of places (pattern 2) so that the group would be moving, but the individuals would be sojourning, and could that be done without handling too many duplicates?

**Comment by stephenhart8** [comment]
You've pointed a very good example of a group of artist sojourning in a place. I think in CIDOC point of view, the group is not sojourning, as it is not a physical person.
In your proposal seems reasonable, but in some cases groups may have multiple or non properties or location?

**Comment by KarineLeonardBrouillet** [comment]
1. Incorporated bodies will always have (theoretically) at least one location because legally to be incorporated you have to be incorporated somewhere I think (this is what determines what laws your company works under, which is why there are a lot of companies that are incorporated in Delaware, for example, because the laws are more accommodating). So in the case of incorporated bodies, the pattern should always work as the lowest broadest location will be the country. However, for companies that are not incorporated it might be more tricky because the pattern might not fit. 
2. I think the group might have no location and only have a series of sojourns just as a person would? This makes me realise that individuals also sometimes do not have customary residences so it might be problematic to articulate the sojourn itself around the concept of a customary residence?

**Comment by Habennin** [comment]
I think use case 1 goes beyond current modelling. You can use p74 has former or current residence and multi instantiate it, if you have a temporal information. Otherwise, you are going to need new event classes to indicate the act of 'setting up shop' at a certain location.

In use case 2, if the group never had a specific place, then yes, it would be true to reality to model only the events that they engaged in and where those events were located.

**Comment by stephenhart8** [comment]
This discussion is continued in #31 
I therefor close this one
