### ISSUE TITLE
Issue #20 – What to do with the “Remarks” field in some museums?

### ISSUE THREAD

**Issue by chin-rcip** [chin-rcip/chin-rcip#20]
Most of the museum dataset have a kind of miscellaneous field, often called "remarks" that contains some various information that could not be documented elsewhere in their dataset (this is the case in Artist in Canada). This kind of field contains various kind of information and is therefore not consistent.
What should CHIN do with this kind of information? Should CHIN create a "remark" field?

**Comment by KarineLeonardBrouillet** [comment]
Yes it would be useful especially if we consider text mining some of these description in the future to extract more data.

**Comment by Habennin** [comment]
There is already a pattern for that in your modelling. I mean you can use the

E73 -> p 190 -> Literal
E73 -> p2 has type ->E55 'Curatorial Note'
E73 -> p2 has type -> E55 'Curatorial Note' - > p2 ->E55 Description
E73 -> p94i -> E65 -> p14 ->E39 

pattern in order to model this. Chin could coin its own uri for 'curatorial note' but I think AAT is also doing this for linked.art.

**Comment by stephenhart8** [comment]
This "Curatorial Note" pattern has been added to the TM 2.0 and will be tested in the following month.
I propose to close this issue.

**Comment by Habennin** [comment]
+1 to closing

**Comment by illip** [comment]
@stephenhart8 +1 to closing!

**Comment by stephenhart8** [comment]
By general agreement, I close this issue.
